name: tetris CI

on: workflow_dispatch


jobs:
  windows_job:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./tetris
    steps:
      - uses: actions/checkout@v4

      # Setup the Windows build environment
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Setup GraalVM built by Gluon
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make native-image directory
        run: New-Item -Path "native-image" -ItemType Directory

      - name: Gluon build
        run: mvn -Pwindows gluonfx:build

      - name: Copy native image to native-image directory
        run: Copy-Item -Path "target/gluonfx/x86_64-windows/tetris.exe" -Destination "native-image/"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: tetris-windows-artifact
          path: tetris/native-image/


  mac_job:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./tetris
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM built by Gluon
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arch: 'aarch64'

      - name: Make native-image directory
        run: mkdir native-image

      - name: Gluon build
        run: mvn -Pmac gluonfx:build

      - name: Copy native image to native-image directory
        run: cp -r target/gluonfx/aarch64-darwin/tetris* native-image

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: tetris-mac-artifact
          path: tetris/native-image/


  linux_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tetris
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM built by Gluon
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Install extra required packaged on top of ubuntu-latest
      - name: Install libraries
        run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Make native-image directory
        run: mkdir native-image

      - name: Gluon build
        run: mvn -Plinux gluonfx:build

      - name: Copy native image to native-image directory
        run: cp -r target/gluonfx/x86_64-linux/tetris native-image

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: tetris-linux-artifact
          path: tetris/native-image/